version: '3'

services:

  app:
    image: registry.outlandish.com/nicksellen/hello-nodejs/app
    build: .
    networks:
      - application
    restart: always
    ports:
      - "3010:80"

networks:
  application:
